import { SchemaAuthorityType, SchemaAuthorities, SchemaName } from '../../types'
import { Schema } from '../useLoadApp'

/* NOTE: read/update are checked using access properties on a model */

export const ALL_AUTHORITY = 'ALL'
// user can create model if they have any of the following authorities
const createAuthTypes = [
    SchemaAuthorityType.CREATE,
    SchemaAuthorityType.CREATE_PRIVATE,
    SchemaAuthorityType.CREATE_PUBLIC,
] as const

const canCreateAuthTypes = new Set<SchemaAuthorityType>(createAuthTypes)
type CreateAuthType = (typeof createAuthTypes)[number]

export type Operation = CreateAuthType | SchemaAuthorityType.DELETE

const nonCreateableSchemas = new Set<SchemaName>([
    SchemaName.categoryOptionCombo,
])

export const isNonCreateableSchema = (schemaName: SchemaName) => {
    return nonCreateableSchemas.has(schemaName)
}

export const hasAuthorityForOperation = (
    operation: Operation,
    schemaAuthorities: SchemaAuthorities,
    userAuthorities: Set<string>
) => {
    if (userAuthorities.has(ALL_AUTHORITY)) {
        return true
    }

    const authoritiesNeeded = schemaAuthorities?.find((auth) => {
        // if operation is CREATE it can be any of types in canCreateAuthTypes
        if (operation === SchemaAuthorityType.CREATE) {
            return canCreateAuthTypes.has(auth.type)
        }
        return auth.type === operation
    })?.authorities

    if (!authoritiesNeeded) {
        return false
    }
    return authoritiesNeeded.some((auth) => userAuthorities.has(auth))
}

/**
 * Always prevent creation of categoryOptionCombo, since these are generated by server
 */
export function canCreate(schema: Schema, userAuthorities: Set<string>) {
    if (isNonCreateableSchema(schema.singular)) {
        return false
    }
    return hasCreateAuthority(schema.authorities, userAuthorities)
}

export function hasCreateAuthority(
    schemaAuthorities: SchemaAuthorities,
    userAuthorities: Set<string>
) {
    return hasAuthorityForOperation(
        SchemaAuthorityType.CREATE,
        schemaAuthorities,
        userAuthorities
    )
}
