describe('Organisation units form tests', () => {
    describe('Common', () => {
        it('should not submit when a required values is missing ', () => {})
        it('should show an error if name field is too long', () => {})
        it('should show an error if short field is too long', () => {})
        it('should show an error if code field is too long', () => {})
        it('should show an error if comment field is too long', () => {})
        it('should show an error if description field is too long', () => {})
        it('should show an error if contact person field is too long', () => {})
        it('should show an error if address field is too long', () => {})
        it('should show an error if phone number field is too long', () => {})
        it('should show an error if url field is too long', () => {})
        it('should show an error if name field is a duplicate', () => {})
        it('should show an error if short name field is a duplicate', () => {})
        it('should show an error if code field is a duplicate', () => {})
        it('should show an error if opening date is not in required format', () => {})
        it('should show an error if closing date is not in required format', () => {})
        it('should show an error if image was not uploaded correctly', () => {})
        it('should allow to create an org unit as a child of the root org unit', () => {})
        it('should show an error if entering an invalid URL', () => {})
        it('should show an error if longitude is above 90', () => {})
        it('should show an error if longitude is below -90', () => {})
        it('should show an error if latitude is above 180', () => {})
        it('should show an error if latitude is below -180', () => {})
        it('should show an error if email is not valid', () => {})
        it('should show an error if parent org unit is not selected', () => {})
        it('should allow creation of the first org unit', () => {})
        it('should save org unit data sets', () => {})
        it('should save org unit programs', () => {})
    })
    describe('New', () => {
        it('contain all needed field', () => {})
        it('should have a cancel button with a link back to the list view', () => {})
        it('should submit the data', () => {})
    })
    describe('Edit', () => {
        it('contain all needed field prefilled', () => {})
        it('should submit the data and return to the list view on success when a field is changed', () => {})
        it('should do nothing and return to the list view on success when no field is changed', () => {})
        it('should edit org unit data sets', () => {})
        it('should edit org unit programs', () => {})
    })
})
