// generated by https://github.com/Birkbjo/dhis2-open-api-ts
export type * from './generated'
export * from './systemSettings'

export type DisplayableModel = {
    id: string
    displayName: string
    disabled?: boolean
}

export type PartialLoadedDisplayableModel = {
    id: string
    displayName?: string
    disabled?: boolean
}
