import { SmsConfiguration } from './models'

export type SystemSettings = {
    keyDateFormat: string
    keyHideBiWeeklyPeriods: boolean
    keyGoogleMapsApiKey: string
    keyRemoteInstanceUsername: string
    keyFileResourceRetentionStrategy: string
    keyEmailSender: string
    keyAnalysisDigitGroupSeparator: string
    keyCustomLoginPageLogo: boolean
    KeyTrackedEntityInstanceMaxLimit: number
    keyUseCustomLogoBanner: boolean
    keyDashboardContextMenuItemOpenInRelevantApp: boolean
    keyEmailTls: boolean
    keyRemoteInstanceUrl: string
    keyLastSuccessfulSystemMonitoringPush: string
    keyHideDailyPeriods: boolean
    keyDataImportStrictDataSetLocking: boolean
    keyFlag: string
    minPasswordLength: number
    analyticsFinancialYearStart: string
    keyBingMapsApiKey: string
    keyUseCustomLogoFront: boolean
    credentialsExpiresReminderInDays: number
    keySkipDataTypeValidationInAnalyticsTableExport: boolean
    keyHideMonthlyPeriods: boolean
    startModule: string
    ruleEngineAssignOverwrite: boolean
    keyCacheStrategy: string
    keyDataImportRequireCategoryOptionCombo: boolean
    multiOrganisationUnitForms: boolean
    syncMaxAttempts: number
    keyDataImportStrictAttributeOptionCombos: boolean
    keyHideWeeklyPeriods: boolean
    keyGatherAnalyticalObjectStatisticsInDashboardViews: boolean
    credentialsExpiryAlert: boolean
    keyCustomTopMenuLogo: boolean
    keySmsMaxLength: number
    keyLastMonitoringRun: string
    keyAnalyticsMaxLimit: number
    keyLockMultipleFailedLogins: boolean
    lastSuccessfulDataStatistics: string
    keyCountPassiveDashboardViewsInUsageAnalytics: boolean
    keyDashboardContextMenuItemViewFullscreen: boolean
    keyDatabaseServerCpus: number
    keyIncludeZeroValuesInAnalytics: boolean
    keyApplicationFooter: string
    keyDataImportStrictPeriods: boolean
    syncDelayBetweenRemoteServerAvailabilityCheckAttempts: number
    keyIgnoreAnalyticsApprovalYearThreshold: number
    keyDataImportStrictDataSetInputPeriods: boolean
    keySelfRegistrationNoRecaptcha: boolean
    keyCustomCss: string
    applicationTitle: string
    syncSkipSyncForDataChangedBefore: string
    keyAnalysisDisplayProperty: string
    maxPasswordLength: number
    keyDashboardContextMenuItemSwitchViewType: boolean
    keyLastCompleteDataSetRegistrationSyncSuccess: string
    keyMetaDataRepoUrl: string
    keyApplicationNotification: string
    keyLastSuccessfulAnalyticsTablesUpdate: string
    keyUiLocale: string
    keyDbLocale: string
    keyEmailPort: number
    keyRespectMetaDataStartEndDatesInAnalyticsTableExport: boolean
    keyCalendar: string
    keyHideBiMonthlyPeriods: boolean
    keyCacheability: string
    keyDataImportRequireAttributeOptionCombo: boolean
    keyLastSuccessfulAnalyticsTablesRuntime: string
    keyStyle: string
    keyLastSuccessfulResourceTablesUpdate: string
    keyDataImportStrictDataSetApproval: boolean
    keyVersionEnabled: boolean
    factorDeviation: number
    keySqlViewMaxLimit: number
    accountExpiryAlert: boolean
    keyAnalysisRelativePeriod: string
    keyDashboardContextMenuItemShowInterpretationsAndDetails: boolean
    accountExpiresInDays: number
    keyAnalyticsCacheProgressiveTtlFactor: number
    keyLastSuccessfulEventsDataSynch: string
    syncMaxRemoteServerAvailabilityCheckAttempts: number
    keyAllowObjectAssignment: boolean
    keyStopMetadataSync: boolean
    keySmsSetting: SmsConfiguration
    keyDataImportStrictDataElements: boolean
    keyLastSuccessfulDataSynch: string
    keyApplicationIntro: string
    keyDataImportStrictOrganisationUnits: boolean
    helpPageLink: string
    keyDataImportStrictCategoryOptionCombos: boolean
    credentialsExpires: number
    keyAccountRecovery: boolean
    keyCanGrantOwnUserAuthorityGroups: boolean
    keyAcceptanceRequiredForApproval: boolean
    keyRequireAddToView: boolean
    keyAnalyticsCacheTtlMode: string
    startModuleEnableLightweight: boolean
}

export type SystemSettingsKey = keyof SystemSettings
